---
- name: Deploy NGINX Docker Container
  hosts: 172.31.46.151
  become: yes

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Pull NGINX Docker Image
      docker_image:
        name: nginx:latest
        source: pull

    - name: Start NGINX Docker Container
      docker_container:
        name: nginx_container
        image: nginx:latest
        state: started
        ports:
          - "80:80"
        volumes:
          - /path/to/nginx.conf:/etc/nginx/nginx.conf:ro
          - /path/to/html:/usr/share/nginx/html:ro

