---
- name: Deploy React JS Application
  hosts: webservers
  remote_user: root
  become: yes
  
  vars:
    app_name: docker-react
    app_path: /var/www/html/{{ app_name }}
    docker_compose_file: docker-compose.yml
  tasks:
    - name: Clone Git Repository
      git:
        repo: https://github.com/SangyAdhikari/docker-react.git
        dest: "{{ app_path }}"
        version: master
      become: yes
      

    - name: Build and Run Docker Compose
      command: docker-compose -f {{ app_path }}/{{ docker_compose_file }} up -d
      become: yes

       



   

